# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    container_name: db-init-demo-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecret
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_DB: my_liquibase_db
