-- The following is the setup for a persisted HSQL database
--  ** Creating the Application User
CREATE USER EMPLOYEE_APP_USER PASSWORD 'mynonsecretpassw0rd';
ALTER USER EMPLOYEE_APP_USER SET LOCAL true;
CREATE ROLE EMPLOYEEAPPROLE;
GRANT EMPLOYEEAPPROLE TO EMPLOYEE_APP_USER;

-- *** Creating the Database Owner User
CREATE USER DB_OWNER_USER PASSWORD 'mysecret' ADMIN;
ALTER USER DB_OWNER_USER SET LOCAL true;
commit;

SELECT * FROM INFORMATION_SCHEMA.SYSTEM_USERS;
SELECT * FROM INFORMATION_SCHEMA.AUTHORIZATIONS;